// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: proto/plugin/v1/plugin.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NodePluginClient is the client API for NodePlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodePluginClient interface {
	// Meta returns the static descriptor for this node type.
	// Called once at startup during plugin registration.
	Meta(ctx context.Context, in *MetaRequest, opts ...grpc.CallOption) (*MetaResponse, error)
	// Execute runs the node logic for a single invocation.
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
}

type nodePluginClient struct {
	cc grpc.ClientConnInterface
}

func NewNodePluginClient(cc grpc.ClientConnInterface) NodePluginClient {
	return &nodePluginClient{cc}
}

func (c *nodePluginClient) Meta(ctx context.Context, in *MetaRequest, opts ...grpc.CallOption) (*MetaResponse, error) {
	out := new(MetaResponse)
	err := c.cc.Invoke(ctx, "/plugin.v1.NodePlugin/Meta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodePluginClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, "/plugin.v1.NodePlugin/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodePluginServer is the server API for NodePlugin service.
// All implementations must embed UnimplementedNodePluginServer
// for forward compatibility
type NodePluginServer interface {
	// Meta returns the static descriptor for this node type.
	// Called once at startup during plugin registration.
	Meta(context.Context, *MetaRequest) (*MetaResponse, error)
	// Execute runs the node logic for a single invocation.
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	mustEmbedUnimplementedNodePluginServer()
}

// UnimplementedNodePluginServer must be embedded to have forward compatible implementations.
type UnimplementedNodePluginServer struct {
}

func (UnimplementedNodePluginServer) Meta(context.Context, *MetaRequest) (*MetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Meta not implemented")
}
func (UnimplementedNodePluginServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedNodePluginServer) mustEmbedUnimplementedNodePluginServer() {}

// UnsafeNodePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodePluginServer will
// result in compilation errors.
type UnsafeNodePluginServer interface {
	mustEmbedUnimplementedNodePluginServer()
}

func RegisterNodePluginServer(s grpc.ServiceRegistrar, srv NodePluginServer) {
	s.RegisterService(&NodePlugin_ServiceDesc, srv)
}

func _NodePlugin_Meta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodePluginServer).Meta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.NodePlugin/Meta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodePluginServer).Meta(ctx, req.(*MetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodePlugin_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodePluginServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.NodePlugin/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodePluginServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodePlugin_ServiceDesc is the grpc.ServiceDesc for NodePlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodePlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.v1.NodePlugin",
	HandlerType: (*NodePluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Meta",
			Handler:    _NodePlugin_Meta_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _NodePlugin_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/plugin/v1/plugin.proto",
}
