// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: proto/grader/v1/grader.proto

package graderv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GraderPluginClient is the client API for GraderPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GraderPluginClient interface {
	// Meta returns the static descriptor for this grader type.
	// Called once at registration time.
	Meta(ctx context.Context, in *MetaRequest, opts ...grpc.CallOption) (*MetaResponse, error)
	// Grade evaluates data against the grader's criteria and returns a verdict.
	Grade(ctx context.Context, in *GradeRequest, opts ...grpc.CallOption) (*GradeResponse, error)
}

type graderPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewGraderPluginClient(cc grpc.ClientConnInterface) GraderPluginClient {
	return &graderPluginClient{cc}
}

func (c *graderPluginClient) Meta(ctx context.Context, in *MetaRequest, opts ...grpc.CallOption) (*MetaResponse, error) {
	out := new(MetaResponse)
	err := c.cc.Invoke(ctx, "/grader.v1.GraderPlugin/Meta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graderPluginClient) Grade(ctx context.Context, in *GradeRequest, opts ...grpc.CallOption) (*GradeResponse, error) {
	out := new(GradeResponse)
	err := c.cc.Invoke(ctx, "/grader.v1.GraderPlugin/Grade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GraderPluginServer is the server API for GraderPlugin service.
// All implementations must embed UnimplementedGraderPluginServer
// for forward compatibility
type GraderPluginServer interface {
	// Meta returns the static descriptor for this grader type.
	// Called once at registration time.
	Meta(context.Context, *MetaRequest) (*MetaResponse, error)
	// Grade evaluates data against the grader's criteria and returns a verdict.
	Grade(context.Context, *GradeRequest) (*GradeResponse, error)
	mustEmbedUnimplementedGraderPluginServer()
}

// UnimplementedGraderPluginServer must be embedded to have forward compatible implementations.
type UnimplementedGraderPluginServer struct {
}

func (UnimplementedGraderPluginServer) Meta(context.Context, *MetaRequest) (*MetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Meta not implemented")
}
func (UnimplementedGraderPluginServer) Grade(context.Context, *GradeRequest) (*GradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Grade not implemented")
}
func (UnimplementedGraderPluginServer) mustEmbedUnimplementedGraderPluginServer() {}

// UnsafeGraderPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GraderPluginServer will
// result in compilation errors.
type UnsafeGraderPluginServer interface {
	mustEmbedUnimplementedGraderPluginServer()
}

func RegisterGraderPluginServer(s grpc.ServiceRegistrar, srv GraderPluginServer) {
	s.RegisterService(&GraderPlugin_ServiceDesc, srv)
}

func _GraderPlugin_Meta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraderPluginServer).Meta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grader.v1.GraderPlugin/Meta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraderPluginServer).Meta(ctx, req.(*MetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraderPlugin_Grade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraderPluginServer).Grade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grader.v1.GraderPlugin/Grade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraderPluginServer).Grade(ctx, req.(*GradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GraderPlugin_ServiceDesc is the grpc.ServiceDesc for GraderPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GraderPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grader.v1.GraderPlugin",
	HandlerType: (*GraderPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Meta",
			Handler:    _GraderPlugin_Meta_Handler,
		},
		{
			MethodName: "Grade",
			Handler:    _GraderPlugin_Grade_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/grader/v1/grader.proto",
}
